### ISSUE TITLE
Replace parallel_split_test with test-queue

### ISSUE THREAD

**Issue by bootstraponline** [titusfortner/saucer#1]
parallel_split_test has some issues in the way tests are executed.
https://github.com/grosser/parallel_split_test/issues/7

These are resolved in test-queue using the `TEST_QUEUE_SPLIT_GROUPS` flag. Test Queue is also a bit more flexible in how the tests are run (split vs no split).
- TEST_QUEUE_SPLIT_GROUPS

**Comment by titusfortner** [comment]
Hmm, I can take a look at test queue. This wouldn't replace parallel_cucumber.

**Comment by bootstraponline** [comment]
> This wouldn't replace parallel_cucumber.

I think it would. There's a test-queue cucumber runner.

- https://github.com/tmm1/test-queue/blob/master/lib/test_queue/runner/cucumber.rb

**Comment by titusfortner** [comment]
I'll leave this open, but I'm unlikely to put resources into implementing it in the near future. Existing parallelization strategy is good enough for the current intention of this gem. PRs, of course, are welcomed.

**Comment by bootstraponline** [comment]
should probably put a warning or something on the readme that this isn't intended for a production use case?

i've contributed to parallel_split_test and while great for demos, isn't the best option for large suites.

**Comment by titusfortner** [comment]
pulled out this functionality entirely for now
