### ISSUE TITLE
Don't invoke test runner multiple times for each platform

### ISSUE THREAD

**Issue by bootstraponline** [titusfortner/saucer#2]
See [sauce_rspec](https://github.com/bootstraponline/sauce_rspec/blob/master/lib/sauce_rspec/rspec.rb) on how to run all combinations within a single test runner execution. There's now [an upstream rspec core API to make duplicating examples easier.](https://github.com/rspec/rspec-core/commits?author=bootstraponline)

**Comment by titusfortner** [comment]
You're suggesting using rspec example groups instead of rake multitask?

**Comment by bootstraponline** [comment]
No, I'm suggesting a cleaner version of this:

- https://github.com/saucelabs/sauce_ruby/blob/master/lib/sauce/rspec/rspec.rb

The idea is a single test execution takes care of all platforms.

**Comment by titusfortner** [comment]
I'll leave this open, but I'm unlikely to put resources into implementing it in the near future. Existing functionality is good enough for the current intention of this gem. PRs are welcomed.

**Comment by titusfortner** [comment]
pulled out this functionality entirely for now. Will revisit.
