### ISSUE TITLE
Correctly set Sauce Labs job status & use meaningful names

### ISSUE THREAD

**Issue by bootstraponline** [titusfortner/saucer#3]
See https://github.com/bootstraponline/sauce_rspec/blob/master/lib/sauce_rspec/sauce_rspec.rb#L31

**Comment by titusfortner** [comment]
I think this is outside the scope of this gem. I'd like for this to be as test runner agnostic as possible. The gem should make it easy to add things to capabilities, but not auto generate based on harness in use.

**Comment by bootstraponline** [comment]
> I think this is outside the scope of this gem. I'd like for this to be as test runner agnostic as possible.

I disagree, most projects are using RSpec. It's painful to manually setup Jenkins integration, Sauce reporting, etc.

- https://github.com/saucelabs/sauce_ruby/blob/master/lib/sauce/rspec/rspec.rb#L87

**Comment by titusfortner** [comment]
I reconsidered on this one and added support for Cucumber & RSpec.
