### ISSUE TITLE
Provide a working JUnit XML formatter 

### ISSUE THREAD

**Issue by bootstraponline** [titusfortner/saucer#4]
See https://github.com/bootstraponline/rspec_junit

**Comment by titusfortner** [comment]
I think this is also outside the scope of the intention for this gem. 

Between the current Sauce plugin for Jenkins and this gem I'm not sure what functionality you are asking for. Is there some specific tie-in to the gems you've written that requires Sauce data?

**Comment by bootstraponline** [comment]
> I'm not sure what functionality you are asking for

I agree, it's unfortunate that the basic use case isn't understood. I think the visions for this project is sufficiently divergent from the problems I'm solving that there's no overlap in terms of scope.
